local Gun = game.Players.LocalPlayer.Character:FindFirstChildOfClass("Tool")
local Config = Gun:WaitForChild("Configuration")
Config.RecoilMin.Value = 0
Config.RecoilMax.Value = 0
Config.RecoilDecay.Value = 0
Config.TotalRecoilMax.Value = 0
Config.MaxSpread.Value = 0
Config.GravityFactor.Value = 0
Config.ShotCooldown.Value = 0
