loadstring(game:HttpGet('https://raw.githubusercontent.com/GrumpyNemo/RobloxScripts/main/Nemos%20Roblox%20Scripts/NemoHub/main.lua'))()
local pre = ("https://raw.githubusercontent.com/GrumpyNemo/RobloxScripts/main/Nemos%20Roblox%20Scripts/NemoHub/")
local ext = (".lua")
local construct = (pre..game.PlaceId..ext)
wait()
loadstring(game:HttpGet(tostring(construct)))()
